import { ITrade } from "interface/ITrade"

const fakeTrades:ITrade[] = [
    {
        id: 9,
        date: "01-05-2023",
        stock: "CTAG",
        bs: "buy",
        size: 600,
        price: 6,
        fees: 100,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 500,
        risk: 5.9,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: 1259.70,
        status: "open",
    },
    {
        id: 8,
        date: "30-04-2023",
        stock: "REAT",
        bs: "buy",
        size: 420,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: -350.25,
        status: "increased",
    },
    {
        id: 7,
        date: "29-04-2023",
        stock: "CTAG",
        bs: "buy",
        size: 100,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: 980.59,
        status: "decreased",
    },
    {
        id: 6,
        date: "28-04-2023",
        stock: "REAT",
        bs: "sell",
        size: 690,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 500,
        risk: 3.1,
        aop: 85,
        acp: 77,
        rrRatio: 0,
        grossPL: 2100.42,
        status: "open",
    },
    {
        id: 5,
        date: "27-04-2023",
        stock: "REAt",
        bs: "buy",
        size: 100,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 33,
        acp: 47,
        rrRatio: 0,
        grossPL: -750.00,
        status: "increased",
    },
    {
        id: 4,
        date: "26-04-2023",
        stock: "REAT",
        bs: "buy",
        size: 100,
        price: 6,
        fees: 2000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: 2500.00,
        status: "open",
    },
    {
        id: 3,
        date: "25-04-2023",
        stock: "REAT",
        bs: "sell",
        size: 100,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: 2780.43,
        status: "open",
    },
    {
        id: 2,
        date: "24-04-2023",
        stock: "CTAG",
        bs: "sell",
        size: 100,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: 3257.58,
        status: "decreased",
    },
    {
        id: 1,
        date: "23-04-2023",
        stock: "CTAG",
        bs: "buy",
        size: 100,
        price: 6,
        fees: 1000,
        stop: 0,
        target: 0,
        strategy: "swiping",
        value: 50,
        risk: 2.4,
        aop: 43,
        acp: 47,
        rrRatio: 0,
        grossPL: 3780.34,
        status: "increased",
    }
]

function fetchTrades() {
    return fakeTrades;
}

export {
    fetchTrades
}